apiVersion: storage.k8s.io/v1 
kind: StorageClass
metadata: 
  name: ebs-sc 
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstCunsumer
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: ebs-dynamic-pvc
spec:
  storageClassName: "ebs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: frontend
      project: roboshop
  template:
    metadata:
      labels:
        app: frontend
        project: roboshop
    spec: 
      volumes:
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: ebs-dynamic-pvc
      containers:
      - name: frontend
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html

