kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-roboshop-sc  #a single file system can be used by entire company . we will create storage class for roboshop project 
provisioner: efs.csi.aws.com  
parameters:
  provisioningMode:  efs-ap  #Use EFS Access Points for dynamic provisioning.This allows each PVC to get a separate directory and permissions inside the EFS filesystem.
  fileSystemId: fs-0066fd301649ac090 #this is efs file system id
  directoryPerms: "700" #Owner has full access, others none.
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/roboshop" # All PVC directories are created under this folder in EFS. Keeps your project organized and separate from other apps.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-dynamic-roboshop-sc"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these labels belong to deployment
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: nginx
      project: roboshop
      component: frontend
  template: # this is the pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-html
      volumes:
      - name: nginx-html
        persistentVolumeClaim: # this is the PVC
          claimName: efs-dynamic-pvc