apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: efs-static-pv
spec: 
  storageClassName: "" 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi: 
   driver: efs.csi.aws.com
   voluemHandle: fs-0bd3e30fe7cbe9dad
  capacity:
    storage: 10Gi
  volumeMode: Filesystem

---
apiVersion: v1  #this is pvc
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these labels belong to deployment
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: nginx
      project: roboshop
      component: frontend
  template: # this is the pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      volumes:
      - name: nginx-html
        persistentVolumeClaim: # this is the PVC
          claimName: efs-static-pvc
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-html
      

