apiVersion: v1 
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-06203667cb6a95a92
  capacity:
    storage: 10Gi
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web1
spec:
  selector:
    matchLabels:
      app: nginx-stateful # has to match .spec.template.metadata.labels
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-stateful # has to match .spec.selector.matchLabels
    spec:
      volumes: 
      - name: nginx-service
        persistentVolumeClaim:
          claimName: ebs-static-pvc
      containers:
      - name: nginx-stateful
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-service
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-stateless
spec:
  clusterIP: None #headless
  selector:
    app: nginx-stateful
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: http-web-svc # this port belongs to container